### ISSUE TITLE
Needs snort path option

### ISSUE THREAD

**Issue by DigiAngel** [shirkdog/pulledpork3#26] opened 2021-07-19 19:42 UTC
Had to symlink my /opt/snort/bin/snort into /usr/local/bin/ to get pulledpork3 to see what version snort was:
~~~
Loading configuration file: /opt/snort/etc/pulledpork/pulledpork.conf
Traceback (most recent call last):
  File "./pulledpork.py", line 937, in <module>
    main()
  File "./pulledpork.py", line 149, in main
    conf.snort_version = get_snort_version(conf.get('snort_path'))
  File "./pulledpork.py", line 925, in get_snort_version
    log.error('Fatal error determining snort version from binary:' + process.returncode + ' ' + error.strip())
TypeError: can only concatenate str (not "int") to str
~~~

**Comment by colingrady** [comment] 2021-07-19 20:04
Should be fixed w/ latest commits. Looks like you'll need to add your Snort binary path to the config (as an alternative to creating a symlink). The problem is that Snort was not in your $PATH spec.

**Closed by colingrady** 2021-07-19 20:04 UTC
